R:
    kill: pkill -9 "R" # The command to kill R
    path: # The path to R
        portable: R-Portable-Mac/bin/R
        home: R-Portable-Mac # The home dir of R
        local: /Library/Frameworks/lib/R/bin/R 
