R:
    kill: taskkill /im Rscript.exe /f # The command to kill R
    path: # The path to R
        portable: R-Portable-Win\\bin\\RScript.exe
        home: R-Portable-Win # The home dir of R
        local: %ProgramFiles%\\R\\R-4.3.2\\bin\\RScript.exe # Need to update for any version of R
