on:
  push:
    branches: [ "master" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "master" ]
jobs:
  test:
    name: Test on node ${{ matrix.node_version }}, R ${{ matrix.R }}, and  ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
        os: [ubuntu-latest, macos-latest]
        R: ['4.1.3', '4.2.3', '4.3.3']

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node_version }}

    - name: Use R ${{ matrix.R }}
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.R }}
    - name: Setup R dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: shiny
    - name: Setup wine
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt install wine
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install wine-stable --cask
        fi
    - name: Npm install
      run: |
        npm install electron-packager -g 
        npm install
    - name: Package
      run: |
        npm run package-win --if-present
        npm run package-linux --if-present
        if [ "$RUNNER_OS" == "macOS" ]; then
          npm run package-mac --if-present
        fi
    - name: Test with xvfb
      uses: GabrielBB/xvfb-action@v1.6
      with:
        run: |
          npm i -g electron
          npm i -g electron-mocha
          electron-mocha
